language: php
php:
#  - '5.4'
#  - '5.5'
  - '5.6'
  - '7.0'
#  - '7.1'

addons:
  apt:
    packages:
    - rrdcached

before_install: true
#  - sudo apt-get update -q
#  - sudo apt-get install rrdcached -y

install: true

before_script:
  - composer update

script:
  - phpunit

